import Stripe from "stripe";
import handler from "../util/handler";
import { calculateCost } from "../util/cost";

export const main = handler(async (event) => {
  // storage is the number of notes the user wants to store
  // source is the Stripe token for the card
  // that gets generated by calling the Stipe's API to verify the card info is valid
  const { source, storage } = JSON.parse(event.body);
  const amount = calculateCost(storage);
  const description = "Scratch charge";

  //Stripe Secret key from the environment variables
  const stripe = new Stripe(process.env.STRIPE_SECRET_KEY);

  await stripe.charges.create({
    source,
    amount,
    description,
    currency: "usd",
  });

  return { status: true };
});
